[{"commit":{"message":"8286895: InternalError: Exception during analyze"},"files":[{"filename":"src\/jdk.compiler\/share\/classes\/com\/sun\/tools\/javac\/comp\/Flow.java"},{"filename":"test\/langtools\/jdk\/jshell\/ErrorRecoveryTest.java"},{"filename":"test\/langtools\/tools\/javac\/recovery\/NoCrashForError.java"},{"filename":"test\/langtools\/tools\/javac\/recovery\/NoCrashForError.out"}],"sha":"4a4612fa2cf875f39ad905a3b6b836b75e55b488"}]