{"files":[{"patch":"@@ -0,0 +1,46 @@\n+\/*\n+ * Copyright (c) 2022, Oracle and\/or its affiliates. All rights reserved.\n+ * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.\n+ *\n+ * This code is free software; you can redistribute it and\/or modify it\n+ * under the terms of the GNU General Public License version 2 only, as\n+ * published by the Free Software Foundation.\n+ *\n+ * This code is distributed in the hope that it will be useful, but WITHOUT\n+ * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n+ * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n+ * version 2 for more details (a copy is included in the LICENSE file that\n+ * accompanied this code).\n+ *\n+ * You should have received a copy of the GNU General Public License version\n+ * 2 along with this work; if not, write to the Free Software Foundation,\n+ * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.\n+ *\n+ * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA\n+ * or visit www.oracle.com if you need additional information or have any\n+ * questions.\n+ *\/\n+\n+\/*\n+ * @test\n+ * @bug 8282686\n+ * @summary Verify cause handling of SocketException\n+ *\/\n+import java.net.SocketException;\n+\n+public class TestSocketExceptionCtor {\n+    public static void main(String... args) {\n+        String reason = \"reason\";\n+        Throwable cause = new RuntimeException();\n+\n+        testException(new SocketException(cause), cause);\n+    }\n+\n+    private static void testException(SocketException se,\n+                                      Throwable expectedCause) {\n+        var cause = se.getCause();\n+        if (cause != expectedCause) {\n+            throw new RuntimeException(\"Unexpected cause\");\n+        }\n+    }\n+}\n","filename":"test\/jdk\/java\/net\/SocketException\/TestSocketExceptionCtor.java","additions":46,"deletions":0,"binary":false,"changes":46,"status":"added"}]}